using Intent.IArchitect.Agent.Persistence.Model;
using Intent.IArchitect.Agent.Persistence.Model.Common;
using Intent.Modules.Common.Types.Api;

namespace Intent.Modules.OpenApi.Importer.Tests.TestData;

/// <summary>
/// Object Mother factory for PackageModelPersistable instances.
/// Provides mock Intent metadata packages representing existing application state.
/// CRITICAL: ExternalReferences must match those generated by OpenApiPersistableFactory for synchronization tests.
/// </summary>
public static class PackageModels
{
    public static PackageModelPersistable Empty()
    {
        return new PackageModelPersistable
        {
            Classes = []
        };
    }

    public static PackageModelPersistable WithTypeDefinitions()
    {
        var dictionary = ElementPersistable.Create(
            TypeDefinitionModel.SpecializationType, 
            TypeDefinitionModel.SpecializationTypeId, 
            "Dictionary", 
            null);
        dictionary.GenericTypes.AddRange([
            new GenericType { Name = "TKey" }, 
            new GenericType { Name = "TValue" }
        ]);

        return new PackageModelPersistable
        {
            Classes = new List<ElementPersistable>
            {
                ElementPersistable.Create(TypeDefinitionModel.SpecializationType, TypeDefinitionModel.SpecializationTypeId, "string", null),
                ElementPersistable.Create(TypeDefinitionModel.SpecializationType, TypeDefinitionModel.SpecializationTypeId, "int", null),
                ElementPersistable.Create(TypeDefinitionModel.SpecializationType, TypeDefinitionModel.SpecializationTypeId, "long", null),
                ElementPersistable.Create(TypeDefinitionModel.SpecializationType, TypeDefinitionModel.SpecializationTypeId, "decimal", null),
                ElementPersistable.Create(TypeDefinitionModel.SpecializationType, TypeDefinitionModel.SpecializationTypeId, "bool", null),
                ElementPersistable.Create(TypeDefinitionModel.SpecializationType, TypeDefinitionModel.SpecializationTypeId, "guid", null),
                ElementPersistable.Create(TypeDefinitionModel.SpecializationType, TypeDefinitionModel.SpecializationTypeId, "date", null),
                ElementPersistable.Create(TypeDefinitionModel.SpecializationType, TypeDefinitionModel.SpecializationTypeId, "datetime", null),
                ElementPersistable.Create(TypeDefinitionModel.SpecializationType, TypeDefinitionModel.SpecializationTypeId, "datetimeoffset", null),
                dictionary
            }
        };
    }

    public static PackageModelPersistable WithExistingService(string serviceName)
    {
        var package = WithTypeDefinitions();

        var service = ElementPersistable.Create("Service", Guid.NewGuid().ToString(), serviceName, null);
        package.Classes.Add(service);
        
        return package;
    }

    /// <summary>
    /// Creates a package with existing CQRS elements matching PetStore spec.
    /// ExternalReferences match those generated by OpenApiPersistableFactory for PetStore operations.
    /// </summary>
    public static PackageModelPersistable WithPetStoreCQRSElements()
    {
        var package = WithTypeDefinitions();
        var intType = package.Classes.First(c => c.Name == "int");
        var stringType = package.Classes.First(c => c.Name == "string");

        // Create GetPets Query (GET /api/pet)
        var getPetsQuery = ElementPersistable.Create(
            "Query",
            "a2e82376-41a6-48fe-aa4d-ab726f38c98c",
            "GetPets",
            package.Id,
            externalReference: "Pet.GetPets");

        // Create CreatePet Command (POST /api/pet)
        var createPetCommand = ElementPersistable.Create(
            "Command",
            "a9969b2f-8f38-4c69-86a4-6930a0ce0f4e",
            "CreatePet",
            package.Id,
            externalReference: "Pet.CreatePet");

        package.Classes.Add(getPetsQuery);
        package.Classes.Add(createPetCommand);

        return package;
    }

    /// <summary>
    /// Creates a package with existing Service mode elements matching PetStore spec.
    /// ExternalReferences match those generated by OpenApiPersistableFactory for PetStore service.
    /// </summary>
    public static PackageModelPersistable WithPetStoreServiceElements()
    {
        var package = WithTypeDefinitions();

        // Create Pet Service (Service mode uses service name as external reference)
        var petService = ElementPersistable.Create(
            "Service",
            "b1a2c3d4-e5f6-7890-abcd-ef1234567890",
            "Pet",
            package.Id,
            externalReference: "Pet");

        // Create FindPetsByStatus operation (GET /api/pet/findByStatus)
        var findPetsByStatusOp = ElementPersistable.Create(
            "Operation",
            "c2b3d4e5-f6a7-8901-bcde-f12345678901",
            "FindPetsByStatus",
            petService.Id,
            externalReference: "Pet.FindPetsByStatus");

        petService.ChildElements.Add(findPetsByStatusOp);
        package.Classes.Add(petService);

        return package;
    }

    /// <summary>
    /// Creates a package with an existing DTO that matches a schema from an OpenAPI spec.
    /// Used for testing schema synchronization behavior.
    /// </summary>
    public static PackageModelPersistable WithExistingPetDTO()
    {
        var package = WithTypeDefinitions();
        var stringType = package.Classes.First(c => c.Name == "string");
        var intType = package.Classes.First(c => c.Name == "int");

        // Create Pet DTO with ExternalReference matching OpenAPI schema
        var petDto = ElementPersistable.Create(
            "DTO",
            "6ab770d1-2c3c-46b5-a4a1-4dfd7b8c3e76", // DTO specialization type ID
            "Pet",
            package.Id,
            externalReference: "Schemas.Pet");

        // Add Id field
        var idField = ElementPersistable.Create(
            "DTO-Field",
            "3ab91ec0-c2a6-4c46-8742-33dcc0eb51e5", // DTO-Field specialization type ID
            "Id",
            petDto.Id,
            externalReference: "Schemas.Pet.Id");
        idField.TypeReference = new TypeReferencePersistable
        {
            IsCollection = false,
            IsNullable = false,
            TypeId = intType.Id
        };

        // Add Name field
        var nameField = ElementPersistable.Create(
            "DTO-Field",
            "3ab91ec0-c2a6-4c46-8742-33dcc0eb51e5", // DTO-Field specialization type ID
            "Name",
            petDto.Id,
            externalReference: "Schemas.Pet.Name");
        nameField.TypeReference = new TypeReferencePersistable
        {
            IsCollection = false,
            IsNullable = false,
            TypeId = stringType.Id
        };

        petDto.ChildElements.Add(idField);
        petDto.ChildElements.Add(nameField);
        package.Classes.Add(petDto);

        return package;
    }
}
